Post.create(title: "Top 5 Puffin Spots in Iceland", subtitle: "Find out when to see and how to find these adorable funny birds while traveling in Iceland!", picture: "https://images.unsplash.com/photo-1496687421442-315106b0da41?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=48e9a280cae006730ccc076049046ef7&auto=format&fit=crop&w=1050&q=80", postbody: "Lorem ipsum dolor amet salvia freegan authentic mustache, palo santo pork belly trust fund food truck chia plaid post-ironic snackwave. Adaptogen thundercats narwhal humblebrag kickstarter sriracha enamel pin quinoa raclette biodiesel readymade 3 wolf moon plaid paleo. Chartreuse hoodie coloring book thundercats cray. Banjo hot chicken YOLO chillwave. Adaptogen beard seitan asymmetrical pok pok occupy woke trust fund XOXO typewriter. Listicle tote bag PBR&B retro kombucha squid green juice.", user_id: 1, time_created: "2018-01-21 13:33:33")

Post.create(title: "Seljalandsfoss", subtitle: "A beautiful waterfall that you can walk behind (in summer)", picture: "https://images.unsplash.com/photo-1505939374277-8d746c530068?ixlib=rb-0.3.5&s=263330ab7e3dcfb5183ff61ba6ca32b5&auto=format&fit=crop&w=1001&q=80", postbody: "Lorem ipsum dolor amet salvia freegan authentic mustache, palo santo pork belly trust fund food truck chia plaid post-ironic snackwave. Adaptogen thundercats narwhal humblebrag kickstarter sriracha enamel pin quinoa raclette biodiesel readymade 3 wolf moon plaid paleo. Chartreuse hoodie coloring book thundercats cray. Banjo hot chicken YOLO chillwave. Adaptogen beard seitan asymmetrical pok pok occupy woke trust fund XOXO typewriter. Listicle tote bag PBR&B retro kombucha squid green juice.", user_id: 2, time_created: "2017-01-21 13:33:33")

Post.create(title: "Seljalandsfoss", subtitle: "A beautiful waterfall that you can walk behind (in summer)", picture: "https://images.unsplash.com/photo-1477573829233-74cd1c17fa65?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=13a772463885c9632fdd3ed369c216a1&auto=format&fit=crop&w=1050&q=80", postbody: "Lorem ipsum dolor amet salvia freegan authentic mustache, palo santo pork belly trust fund food truck chia plaid post-ironic snackwave. Adaptogen thundercats narwhal humblebrag kickstarter sriracha enamel pin quinoa raclette biodiesel readymade 3 wolf moon plaid paleo. Chartreuse hoodie coloring book thundercats cray. Banjo hot chicken YOLO chillwave. Adaptogen beard seitan asymmetrical pok pok occupy woke trust fund XOXO typewriter. Listicle tote bag PBR&B retro kombucha squid green juice.", user_id: 2, time_created: "2017-01-21 13:33:33")

Post.create(title: "Seljalandsfoss", subtitle: "A beautiful waterfall that you can walk behind (in summer)", picture: "https://images.unsplash.com/photo-1489595672898-26572ba975a3?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=c069b5f3b2494f782f85ae6cbf247b6a&auto=format&fit=crop&w=1000&q=80", postbody: "Lorem ipsum dolor amet salvia freegan authentic mustache, palo santo pork belly trust fund food truck chia plaid post-ironic snackwave. Adaptogen thundercats narwhal humblebrag kickstarter sriracha enamel pin quinoa raclette biodiesel readymade 3 wolf moon plaid paleo. Chartreuse hoodie coloring book thundercats cray. Banjo hot chicken YOLO chillwave. Adaptogen beard seitan asymmetrical pok pok occupy woke trust fund XOXO typewriter. Listicle tote bag PBR&B retro kombucha squid green juice.", user_id: 2, time_created: "2017-01-21 13:33:33")

Post.create(title: "Seljalandsfoss", subtitle: "A beautiful waterfall that you can walk behind (in summer)", picture: "https://images.unsplash.com/photo-1488227402652-00175718582c?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=e85d2a8e7b37f668d068fc4c0194e74f&auto=format&fit=crop&w=1052&q=80", postbody: "Lorem ipsum dolor amet salvia freegan authentic mustache, palo santo pork belly trust fund food truck chia plaid post-ironic snackwave. Adaptogen thundercats narwhal humblebrag kickstarter sriracha enamel pin quinoa raclette biodiesel readymade 3 wolf moon plaid paleo. Chartreuse hoodie coloring book thundercats cray. Banjo hot chicken YOLO chillwave. Adaptogen beard seitan asymmetrical pok pok occupy woke trust fund XOXO typewriter. Listicle tote bag PBR&B retro kombucha squid green juice.", user_id: 2, time_created: "2017-01-21 13:33:33")

Post.create(title: "Seljalandsfoss", subtitle: "A beautiful waterfall that you can walk behind (in summer)", picture: "https://images.unsplash.com/photo-1516470047996-b6dde636095f?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=fd63bead70a2a15649dd8da9e4938fdf&auto=format&fit=crop&w=1050&q=80", postbody: "Lorem ipsum dolor amet salvia freegan authentic mustache, palo santo pork belly trust fund food truck chia plaid post-ironic snackwave. Adaptogen thundercats narwhal humblebrag kickstarter sriracha enamel pin quinoa raclette biodiesel readymade 3 wolf moon plaid paleo. Chartreuse hoodie coloring book thundercats cray. Banjo hot chicken YOLO chillwave. Adaptogen beard seitan asymmetrical pok pok occupy woke trust fund XOXO typewriter. Listicle tote bag PBR&B retro kombucha squid green juice.", user_id: 2, time_created: "2017-01-21 13:33:33")
